laba/config/routes.rb
Rails.application.routes.draw do
  resources :types_of_docs
  resources :types
  resources :addresses
  resources :countries
  resources :documents
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

laba/app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: [:show, :edit, :update, :destroy]

  # GET /types
  # GET /types.json
  def index
    @types = Type.all
  end

  # GET /types/1
  # GET /types/1.json
  def show
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Type was successfully created.' }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1
  # PATCH/PUT /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url, notice: 'Type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_params
      params.require(:type).permit(:name)
    end
end

laba/app/helpers/types_helper.rb
module TypesHelper
end

laba/app/views/types/_form.html.erb
<%= form_with(model: type, local: true) do |form| %>
  <% if type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

laba/app/views/types/edit.html.erb
<h1>Editing Type</h1>

<%= render 'form', type: @type %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

laba/app/views/types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @types.each do |type| %>
      <tr>
        <td><%= type.name %></td>
        <td><%= link_to 'Show', type %></td>
        <td><%= link_to 'Edit', edit_type_path(type) %></td>
        <td><%= link_to 'Destroy', type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Type', new_type_path %>

laba/app/views/types/new.html.erb
<h1>New Type</h1>

<%= render 'form', type: @type %>

<%= link_to 'Back', types_path %>

laba/app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @type.name %>
</p>

<%= link_to 'Edit', edit_type_path(@type) %> |
<%= link_to 'Back', types_path %>