laba/config/routes.rb
Rails.application.routes.draw do
  resources :types_of_docs
  resources :types
  resources :addresses
  resources :countries
  resources :documents
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

laba/app/models/document.rb
class Document < ApplicationRecord
    belongs_to :person, optional: true
    belongs_to :country, optional: true
    belongs_to :types_of_doc
end

laba/app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @types = TypesOfDoc.all
    @peoples = Person.all
    @countries = Country.all
  end

  # GET /documents/new
  def new
    @document = Document.new
    @types = TypesOfDoc.all
    @peoples = Person.all
    @countries = Country.all
  end

  # GET /documents/1/edit
  def edit
    @types = TypesOfDoc.all
    @peoples = Person.all
    @countries = Country.all
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)
    @types = TypesOfDoc.all
    @peoples = Person.all
    @countries = Country.all
    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:number, :serial, :source, :people_id, :date, :countries_id, :types_of_doc_id)
    end
end

laba/app/helpers/documents_helper.rb
module DocumentsHelper
end

laba/app/views/documents/_form.html.erb
<%= form_with(model: document, local: true) do |form| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="field">
    <%= form.label :types_of_doc_id %>
  <%= form.select :types_of_doc_id , @types.collect {|c| [ c.id, c.id ] }%>
</div>

  <div class="field">
    <%= form.label :serial %>
    <%= form.text_field :serial %>
  </div>

  <div class="field">
    <%= form.label :source %>
    <%= form.text_field :source %>
  </div>

  <div class="field">
    <%= form.label :people_id %>
    <%= form.select :people_id , @peoples.collect {|c| [ c.last_name, c.id ] }%>

  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :countries_id %>
    <%= form.select :countries_id , @countries.collect {|c| [ c.name, c.id ] }%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

laba/app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

laba/app/views/documents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Documents</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Type</th>
      <th>Serial</th>
      <th>Source</th>
      <th>People</th>
      <th>Date</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.number %></td>
        <td><%= document.type %></td>
        <td><%= document.serial %></td>
        <td><%= document.source %></td>
        <td><%= document.people_id %></td>
        <td><%= document.date %></td>
        <td><%= document.country %></td>
        <td><%= link_to 'Show', document %></td>
        <td><%= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_document_path %>

laba/app/views/documents/new.html.erb
<h1>New Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Back', documents_path %>

laba/app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @document.number %>
</p>

<p>
  <strong>Type:</strong>
  <%= @document.type %>
</p>

<p>
  <strong>Serial:</strong>
  <%= @document.serial %>
</p>

<p>
  <strong>Source:</strong>
  <%= @document.source %>
</p>

<p>
  <strong>People:</strong>
  <%= @document.people_id %>
</p>

<p>
  <strong>Date:</strong>
  <%= @document.date %>
</p>

<p>
  <strong>Country:</strong>
  <%= @document.country %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>