laba/config/routes.rb
Rails.application.routes.draw do
  resources :types_of_docs
  resources :types
  resources :addresses
  resources :countries
  resources :documents
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

laba/app/models/types_of_doc.rb
class TypesOfDoc < ApplicationRecord
    has_many :document
end

laba/app/controllers/types_of_docs_controller.rb
class TypesOfDocsController < ApplicationController
  before_action :set_types_of_doc, only: [:show, :edit, :update, :destroy]

  # GET /types_of_docs
  # GET /types_of_docs.json
  def index
    @types_of_docs = TypesOfDoc.all
  end

  # GET /types_of_docs/1
  # GET /types_of_docs/1.json
  def show
  end

  # GET /types_of_docs/new
  def new
    @types_of_doc = TypesOfDoc.new
  end

  # GET /types_of_docs/1/edit
  def edit
  end

  # POST /types_of_docs
  # POST /types_of_docs.json
  def create
    @types_of_doc = TypesOfDoc.new(types_of_doc_params)

    respond_to do |format|
      if @types_of_doc.save
        format.html { redirect_to @types_of_doc, notice: 'Types of doc was successfully created.' }
        format.json { render :show, status: :created, location: @types_of_doc }
      else
        format.html { render :new }
        format.json { render json: @types_of_doc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types_of_docs/1
  # PATCH/PUT /types_of_docs/1.json
  def update
    respond_to do |format|
      if @types_of_doc.update(types_of_doc_params)
        format.html { redirect_to @types_of_doc, notice: 'Types of doc was successfully updated.' }
        format.json { render :show, status: :ok, location: @types_of_doc }
      else
        format.html { render :edit }
        format.json { render json: @types_of_doc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types_of_docs/1
  # DELETE /types_of_docs/1.json
  def destroy
    @types_of_doc.destroy
    respond_to do |format|
      format.html { redirect_to types_of_docs_url, notice: 'Types of doc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_types_of_doc
      @types_of_doc = TypesOfDoc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def types_of_doc_params
      params.fetch(:types_of_doc, {})
    end
end

laba/app/helpers/types_of_docs_helper.rb
module TypesOfDocsHelper
end

laba/app/views/types_of_docs/_form.html.erb
<%= form_with(model: types_of_doc, local: true) do |form| %>
  <% if types_of_doc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(types_of_doc.errors.count, "error") %> prohibited this types_of_doc from being saved:</h2>

      <ul>
      <% types_of_doc.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

laba/app/views/types_of_docs/edit.html.erb
<h1>Editing Types Of Doc</h1>

<%= render 'form', types_of_doc: @types_of_doc %>

<%= link_to 'Show', @types_of_doc %> |
<%= link_to 'Back', types_of_docs_path %>

laba/app/views/types_of_docs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Types Of Docs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @types_of_docs.each do |types_of_doc| %>
      <tr>
        <td><%= link_to 'Show', types_of_doc %></td>
        <td><%= link_to 'Edit', edit_types_of_doc_path(types_of_doc) %></td>
        <td><%= link_to 'Destroy', types_of_doc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Types Of Doc', new_types_of_doc_path %>

laba/app/views/types_of_docs/new.html.erb
<h1>New Types Of Doc</h1>

<%= render 'form', types_of_doc: @types_of_doc %>

<%= link_to 'Back', types_of_docs_path %>

laba/app/views/types_of_docs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_types_of_doc_path(@types_of_doc) %> |
<%= link_to 'Back', types_of_docs_path %>